---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: document
  path: _data/resources.json
  label: Resources
  read_only: true
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
instant_preview: true
build:
  preview_env:
  - ELEVENTY_ENV=staging
  preview_output_directory: _site
  instant_preview_command: eleventy --serve --output=_site
  preview_docker_image: node:10
  mount_path: "/srv"
